name: My first workflow
on:
  push:
    branches:
      - 'v[0-9]+\.[0-9]+'

jobs: 
  my_first_wf:
    if: ${{ !startsWith(github.event.head_commits.message,'#NORUN')  }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Check for #NORUN in commit message
        run: |
          if [[ "${{ contains(github.event.commits[0].message, '#NORUN') }}" == "true" ]]; then
            echo "#NORUN found. Exiting workflow."
            exit 1
          else
            echo "#NORUN not found. Continuing workflow."
          fi


      - name: Print commit message
        run: echo "${{ github.event.head_commit.message }}"

      - name: Check for norun
        run: |
          if [[ "${{ contains(github.event.head_commit.message, '#NORUN') }}" == "true" ]]; then
            echo "#NORUN found in commit message."
          else
            echo "#NORUN not found in commit message."
          fi

      - name: Checkout Codes
        id: checkout_code
        uses: actions/checkout@v3

      - name: list directory
        id: list_directory
        run: echo "$(ls -l)"

      - name: Run Trivy Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          output: 'trivy-results.txt'
          severity: 'HIGH'

      - name: Check error
        id: check_error_code
        run: cat trivy-results.txt
  


      


   

        