name: My first workflow
on:
  push:
    branches:
      - 'v[0-9]+\.[0-9]+'

jobs: 
  Build_and_push:
    if: ${{ startsWith(github.event.head_commit.message,'#NORUN') == false  }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Codes
        id: checkout_code
        uses: actions/checkout@v3

      - name: list directory
        id: list_directory
        run: echo "$(ls -l)"

      - name: Run Trivy Scanner
        id: trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          exit-code: 1
          output: 'trivy-results.txt'
          severity: 'HIGH,CRITICAL'
        continue-on-error: true

      - name: Print Trivy Results
        id: print_trivy_results
        run: cat trivy-results.txt
          
      # - name: If Trivy is failure
      #   if: steps.trivy.outcome == 'failure'
      #   id: slack
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_CHANNEL: general
      #     SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
      #     SLACK_ICON: https://github.com/rtCamp.png?size=48
      #     SLACK_MESSAGE: 'Failed trivy scan, see uploaded report'
      #     SLACK_TITLE: Post Title
      #     SLACK_USERNAME: rtCamp
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      # - name: Send report
      #   if: steps.trivy.outcome == 'failure'
      #   id: slack_send_report
      #   uses: MeilCli/slack-upload-file@v3
      #   with:
      #     slack_token: ${{ secrets.SLACK_TOKEN }}
      #     channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
      #     file_path: 'trivy-results.txt'
      #     initial_comment: 'Scan report by user'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: calvin01/app:latest



          

           
      
   

     


      


   

        