name: My first workflow
on:
  push:
    branches:
      - 'v[0-9]+\.[0-9]+'

jobs: 
  my_first_wf:
    if: ${{ startsWith(github.event.head_commits.message,'#NORUN') == false  }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Print commit message
        run: echo "${{ github.event.head_commit.message }}"

      - name: Check for norun
        run: |
          if [[ "${{ contains(github.event.head_commit.message, '#NORUN') }}" == "true" ]]; then
            echo "#NORUN found in commit message."
          else
            echo "#NORUN not found in commit message."
          fi

      - name: Checkout Codes
        id: checkout_code
        uses: actions/checkout@v3

      - name: list directory
        id: list_directory
        run: echo "$(ls -l)"

      - name: Run Trivy Scanner
        id: trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          exit-code: 1
          output: 'trivy-results.txt'
          severity: 'HIGH,CRITICAL'
        continue-on-error: true

      - name: Print Trivy Results
        id: print_trivy_results
        run: cat trivy-results.txt
          
      - name: If Trivy is failure
        if: steps.trivy.outcome == 'failure'
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "text": "Trivy detected vulnerabilities!", 
              "key": "value",
              "foo": "bar"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          

           
      
   

  


      


   

        