name: My first workflow
on:
  push:
    branches:
      - 'v[0-9]+\.[0-9]+'

jobs: 
  my_first_wf:
    if: contains(${{github.event.head_commit.message}},'#NORUN') == false
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Codes
        id: checkout_code
        uses: actions/checkout@v3

      - name: list directory
        id: list_directory
        run: echo "$(ls -l)"

      - name: Run Trivy Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          output: 'trivy-results.txt'
          severity: 'HIGH'

      - name: Check error
        id: check_error_code
        run: echo "($?)"



      


